name        : libxrandr
version     : 1.4.2
release     : 6
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libXrandr-1.4.2.tar.bz2 : caa7b31ac769be51a532343c65376f1d4df3f307afaed58e34fb5e82e8b825ad
license     :
    - MIT
summary     : X11 RandR extension library
builddeps   :
    - pkgconfig(randrproto)
    - pkgconfig32(xext)
    - pkgconfig32(xrender)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
description : |
    libXrandr provides an X Window System client interface to the RandR extension to the X protocol. The RandR extension allows for run-time configuration of display attributes such as resolution, rotation, and reflection.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
