name       : libxrandr
version    : 1.5.3
release    : 15
source     :
    - https://www.x.org/releases/individual/lib/libXrandr-1.5.3.tar.gz : 3ad316c1781fe2fe22574b819e81f0eff087a8560377f521ba932238b41b251f
license    : MIT
component  : xorg.library
summary    : X11 RandR extension library
description: |
    libXrandr provides an X Window System client interface to the RandR extension to the X protocol. The RandR extension allows for run-time configuration of display attributes such as resolution, rotation, and reflection.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(xext)
    - pkgconfig32(xrender)
    - pkgconfig32(x11)
    - pkgconfig(xproto)
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
