name       : libxrandr
version    : 1.5.2
release    : 13
source     :
    - https://www.x.org/releases/individual/lib/libXrandr-1.5.2.tar.gz : 3f10813ab355e7a09f17e147d61b0ce090d898a5ea5b5519acd0ef68675dcf8e
license    : MIT
component  : xorg.library
summary    : X11 RandR extension library
description: |
    libXrandr provides an X Window System client interface to the RandR extension to the X protocol. The RandR extension allows for run-time configuration of display attributes such as resolution, rotation, and reflection.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(xext)
    - pkgconfig32(xrender)
    - pkgconfig32(x11)
    - pkgconfig(xproto)
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
