name        : libxrandr
version     : 1.5.0
release     : 7
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libXrandr-1.5.0.tar.bz2 : 6f864959b7fc35db11754b270d71106ef5b5cf363426aa58589cb8ac8266de58
license     :
    - MIT
summary     : X11 RandR extension library
component   : xorg.library
builddeps   :
    - pkgconfig(randrproto)
    - pkgconfig(xextproto)
    - pkgconfig32(xext)
    - pkgconfig(xext)
    - pkgconfig32(xrender)
    - pkgconfig(xrender)
    - pkgconfig32(x11)
    - pkgconfig(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
optimize    : speed
patterns    :
    - devel:
        - /usr/share/man
description : |
    libXrandr provides an X Window System client interface to the RandR extension to the X protocol. The RandR extension allows for run-time configuration of display attributes such as resolution, rotation, and reflection.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
